export type PhotosType = {
  src: string;
  alt: string;
};

export type PostsType = {
  title: string;
  data: string;
  category: string[];
  photos: PhotosType[];
};

export const posts = [
  {
    title: 'Лыжи Морозко 4',
    data: '17 февраля 2024 года',
    category: ['all', 'nizh'],
    photos: [
      { src: '/nizh/ligi42024/0.jpg', alt: 'Лыжи Морозко 4' },
      { src: '/nizh/ligi42024/1.jpg', alt: '' },
      { src: '/nizh/ligi42024/2.jpg', alt: '' },
      { src: '/nizh/ligi42024/3.jpg', alt: '' },
      { src: '/nizh/ligi42024/4.jpg', alt: '' },
      { src: '/nizh/ligi42024/5.jpg', alt: '' },
      { src: '/nizh/ligi42024/6.jpg', alt: '' },
      { src: '/nizh/ligi42024/7.jpg', alt: '' },
      { src: '/nizh/ligi42024/8.jpg', alt: '' },
      { src: '/nizh/ligi42024/9.jpg', alt: '' },
      { src: '/nizh/ligi42024/10.jpg', alt: '' },
      { src: '/nizh/ligi42024/11.jpg', alt: 'Традиционное селфи «<Безумцы»' },
      { src: '/nizh/ligi42024/12.jpg', alt: '' },
    ],
  },

  {
    title: 'Йошкар-Ола',
    data: '9-11 января 2024 года',
    category: ['all', 'mariel'],
    photos: [
      { src: '/mariel/yola/0.jpg', alt: '' },
      { src: '/mariel/yola/1.jpg', alt: '' },
      { src: '/mariel/yola/2.jpg', alt: '' },
      { src: '/mariel/yola/3.jpg', alt: '' },
      { src: '/mariel/yola/4.jpg', alt: '' },
      { src: '/mariel/yola/5.jpg', alt: '' },
      { src: '/mariel/yola/6.jpg', alt: '' },
      { src: '/mariel/yola/7.jpg', alt: '' },
      { src: '/mariel/yola/8.jpg', alt: '' },
      { src: '/mariel/yola/9.jpg', alt: '' },
      { src: '/mariel/yola/10.jpg', alt: '' },
      { src: '/mariel/yola/11.jpg', alt: '' },
      { src: '/mariel/yola/12.jpg', alt: '' },
      { src: '/mariel/yola/13.jpg', alt: '' },
      { src: '/mariel/yola/14.jpg', alt: '' },
      { src: '/mariel/yola/15.jpg', alt: '' },
      { src: '/mariel/yola/16.jpg', alt: '' },
      { src: '/mariel/yola/17.jpg', alt: '' },
      { src: '/mariel/yola/18.jpg', alt: '' },
      { src: '/mariel/yola/19.jpg', alt: '' },
      { src: '/mariel/yola/20.jpg', alt: '' },
      { src: '/mariel/yola/21.jpg', alt: '' },
      { src: '/mariel/yola/22.jpg', alt: '' },
      { src: '/mariel/yola/23.jpg', alt: '' },
      { src: '/mariel/yola/24.jpg', alt: '' },
      { src: '/mariel/yola/25.jpg', alt: '' },
      { src: '/mariel/yola/26.jpg', alt: '' },
      { src: '/mariel/yola/27.jpg', alt: '' },
      { src: '/mariel/yola/28.jpg', alt: '' },
      { src: '/mariel/yola/29.jpg', alt: '' },
      { src: '/mariel/yola/30.jpg', alt: '' },
      { src: '/mariel/yola/31.jpg', alt: '' },
      { src: '/mariel/yola/32.jpg', alt: '' },
      { src: '/mariel/yola/33.jpg', alt: '' },
      { src: '/mariel/yola/34.jpg', alt: '' },
      { src: '/mariel/yola/35.jpg', alt: '' },
      { src: '/mariel/yola/36.jpg', alt: '' },
      { src: '/mariel/yola/37.jpg', alt: '' },
      { src: '/mariel/yola/38.jpg', alt: '' },
      { src: '/mariel/yola/39.jpg', alt: '' },
      { src: '/mariel/yola/40.jpg', alt: '' },
      { src: '/mariel/yola/41.jpg', alt: '' },
      { src: '/mariel/yola/42.jpg', alt: '' },
      { src: '/mariel/yola/43.jpg', alt: '' },
      { src: '/mariel/yola/44.jpg', alt: '' },
      { src: '/mariel/yola/45.jpg', alt: '' },
      { src: '/mariel/yola/46.jpg', alt: '' },
      { src: '/mariel/yola/47.jpg', alt: '' },
      { src: '/mariel/yola/48.jpg', alt: '' },
      { src: '/mariel/yola/49.jpg', alt: '' },
      { src: '/mariel/yola/50.jpg', alt: '' },
      { src: '/mariel/yola/51.jpg', alt: '' },
      { src: '/mariel/yola/52.jpg', alt: '' },
      { src: '/mariel/yola/53.jpg', alt: '' },
      { src: '/mariel/yola/54.jpg', alt: '' },
      { src: '/mariel/yola/55.jpg', alt: '' },
      { src: '/mariel/yola/56.jpg', alt: '' },
      { src: '/mariel/yola/57.jpg', alt: '' },
      { src: '/mariel/yola/58.jpg', alt: '' },
      { src: '/mariel/yola/59.jpg', alt: '' },
      { src: '/mariel/yola/60.jpg', alt: '' },
      { src: '/mariel/yola/61.jpg', alt: '' },
      { src: '/mariel/yola/62.jpg', alt: '' },
      { src: '/mariel/yola/63.jpg', alt: '' },
      { src: '/mariel/yola/64.jpg', alt: '' },
      { src: '/mariel/yola/65.jpg', alt: '' },
      { src: '/mariel/yola/66.jpg', alt: '' },
      { src: '/mariel/yola/67.jpg', alt: '' },
      { src: '/mariel/yola/68.jpg', alt: '' },
      { src: '/mariel/yola/69.jpg', alt: '' },
      { src: '/mariel/yola/70.jpg', alt: '' },
      { src: '/mariel/yola/71.jpg', alt: '' },
    ],
  },
  {
    title: 'Лыжи Снежинка 3',
    data: '4 февраля 2024 года',
    category: ['all', 'nizh'],
    photos: [
      { src: '/nizh/ligi32024/0.jpg', alt: 'Лыжи Снежинка 3' },
      { src: '/nizh/ligi32024/1.jpg', alt: '' },
      { src: '/nizh/ligi32024/2.jpg', alt: '' },
      { src: '/nizh/ligi32024/3.jpg', alt: '' },
      { src: '/nizh/ligi32024/4.jpg', alt: '' },
      { src: '/nizh/ligi32024/5.jpg', alt: '' },
      { src: '/nizh/ligi32024/6.jpg', alt: '' },
      { src: '/nizh/ligi32024/7.jpg', alt: '' },
      { src: '/nizh/ligi32024/8.jpg', alt: '' },
      { src: '/nizh/ligi32024/9.jpg', alt: '' },
      { src: '/nizh/ligi32024/10.jpg', alt: '' },
      { src: '/nizh/ligi32024/11.jpg', alt: '' },
      { src: '/nizh/ligi32024/12.jpg', alt: '' },
      { src: '/nizh/ligi32024/13.jpg', alt: '' },
      { src: '/nizh/ligi32024/14.jpg', alt: '' },
      { src: '/nizh/ligi32024/15.jpg', alt: '' },
      { src: '/nizh/ligi32024/16.jpg', alt: '' },
      { src: '/nizh/ligi32024/17.jpg', alt: '' },
      { src: '/nizh/ligi32024/18.jpg', alt: '' },
      { src: '/nizh/ligi32024/19.jpg', alt: '' },
    ],
  },

  {
    title: 'Лыжи Морозко 2',
    data: '21 января 2024 года',
    category: ['all', 'nizh'],
    photos: [
      { src: '/nizh/ligi22024/0.jpg', alt: 'Лыжи Морозко 2' },
      { src: '/nizh/ligi22024/1.jpg', alt: '' },
      { src: '/nizh/ligi22024/2.jpg', alt: '' },
      { src: '/nizh/ligi22024/3.jpg', alt: '' },
      { src: '/nizh/ligi22024/4.jpg', alt: '' },
      { src: '/nizh/ligi22024/5.jpg', alt: '' },
      { src: '/nizh/ligi22024/6.jpg', alt: '' },
      { src: '/nizh/ligi22024/7.jpg', alt: 'Традиционное селфи «Японцы»' },
      { src: '/nizh/ligi22024/8.jpg', alt: '' },
      { src: '/nizh/ligi22024/9.jpg', alt: '' },
      { src: '/nizh/ligi22024/10.jpg', alt: '' },
    ],
  },
  {
    title: 'Лыжи Морозко 1',
    data: '14 января 2024 года',
    category: ['all', 'nizh'],
    photos: [
      { src: '/nizh/ligi12024/0.jpg', alt: 'Лыжи Морозко 1' },
      { src: '/nizh/ligi12024/1.jpg', alt: '' },
      { src: '/nizh/ligi12024/2.jpg', alt: '' },
      { src: '/nizh/ligi12024/3.jpg', alt: '' },
      { src: '/nizh/ligi12024/4.jpg', alt: '' },
      { src: '/nizh/ligi12024/5.jpg', alt: '' },
      { src: '/nizh/ligi12024/6.jpg', alt: 'Традиционное селфи «Обезьянки»' },
      { src: '/nizh/ligi12024/7.jpg', alt: 'Традиционное селфи «Зайки»' },
    ],
  },
  {
    title: 'Благовещенский монастырь',
    data: '8 января 2024 года',
    category: ['all', 'nizh'],
    photos: [
      { src: '/nizh/blagovest/0.jpg', alt: 'Благовещенский монастырь' },
      { src: '/nizh/blagovest/1.jpg', alt: '' },
      { src: '/nizh/blagovest/2.jpg', alt: '' },
      { src: '/nizh/blagovest/3.jpg', alt: '' },
      { src: '/nizh/blagovest/4.jpg', alt: '' },
      { src: '/nizh/blagovest/5.jpg', alt: '' },
      { src: '/nizh/blagovest/6.jpg', alt: '' },
      { src: '/nizh/blagovest/7.jpg', alt: '' },
      { src: '/nizh/blagovest/8.jpg', alt: '' },
      { src: '/nizh/blagovest/9.jpg', alt: '' },
      { src: '/nizh/blagovest/10.jpg', alt: '' },
      { src: '/nizh/blagovest/11.jpg', alt: '' },
      { src: '/nizh/blagovest/12.jpg', alt: '' },
      { src: '/nizh/blagovest/13.jpg', alt: '' },
      { src: '/nizh/blagovest/14.jpg', alt: '' },
      { src: '/nizh/blagovest/15.jpg', alt: '' },
    ],
  },
  {
    title: 'С Рождеством!',
    data: '7 января 2024 года',
    category: ['all', 'nizh'],
    photos: [
      { src: '/nizh/rogdestvo/0.jpg', alt: 'С Рождеством!' },
      { src: '/nizh/rogdestvo/1.jpg', alt: '' },
      { src: '/nizh/rogdestvo/2.jpg', alt: '' },
    ],
  },
  {
    title: 'Юрино Замок Шереметевых',
    data: '6 января 2024 года',
    category: ['all', 'mariel'],
    photos: [
      {
        src: '/mariel/urino/0.jpg',
        alt: 'Замок Шереметева включен в энциклопедию путешествий Русского географического общества «Где я должен побывать, чтобы познать Россию». Он также вошёл в топ-100 мест России, которые надо увидеть по версии журнала GEO',
      },
      { src: '/mariel/urino/1.jpg', alt: 'Западные ворота.' },
      { src: '/mariel/urino/2.jpg', alt: 'Проект архитектора Альфреда Парланда.' },
      {
        src: '/mariel/urino/3.jpg',
        alt: 'Экстравагантная эклектика с богатой пластикой фасадов. В облике замка удивительно сочетаются черты неоготики, русского узорочья и мавританские мотивы.',
      },
      { src: '/mariel/urino/4.jpg', alt: '' },
      { src: '/mariel/urino/5.jpg', alt: '' },
      { src: '/mariel/urino/6.jpg', alt: '' },
      {
        src: '/mariel/urino/7.jpg',
        alt: 'В подвале замка топилась большая печь. Горячий воздух по воздуховодам в стенах поднимался вверх и выходил через вьюшки в комнаты. Вьюшки можно было закрывать и открывать, если холодно.',
      },
      {
        src: '/mariel/urino/8.jpg',
        alt: 'Два перехода. На переднем плане господский: широкий и красивый. На заднем плане для прислуги: узкий и низкий, чтобы не встречаться. Внизу - итальянский дворик.',
      },
      { src: '/mariel/urino/9.jpg', alt: 'Михайло-Архангельская церковь.' },
      { src: '/mariel/urino/10.jpg', alt: 'Ухо желаний.' },
      { src: '/mariel/urino/11.jpg', alt: 'Шереметевский кот.' },
      { src: '/mariel/urino/12.jpg', alt: 'Герб Шереметевых.' },
      {
        src: '/mariel/urino/13.jpg',
        alt: 'Репродукции. Практически все мы только вчера видели в музее. Вот, оказывается, откуда они.',
      },
      { src: '/mariel/urino/14.jpg', alt: 'Граф Борис Шереметев.' },
      {
        src: '/mariel/urino/15.jpg',
        alt: 'Камин Большой гостиной облицован панелями с раскопок одного из дворцов Помпеи.',
      },
      {
        src: '/mariel/urino/16.jpg',
        alt: 'Вид камина был другой. Слева и справа стояли атлант и кариатида. Их выломали и повезли в Нижний, но они пропали. Плитки положили криво.',
      },
      {
        src: '/mariel/urino/17.jpg',
        alt: 'Родной пол большой гостинной. Мраморная крошка. Рисунок пола разлинован для танцев.',
      },
      { src: '/mariel/urino/18.jpg', alt: 'Мавританский кабинет. Только растительный орнамент.' },
      {
        src: '/mariel/urino/19.jpg',
        alt: 'Потолок мавританского кабинета. Орнамент в каждой ячейке уникален.',
      },
      { src: '/mariel/urino/20.jpg', alt: '' },
      {
        src: '/mariel/urino/21.jpg',
        alt: 'Зимний сад. В центре стояла огромная пальма. В подвалы ведёт веерная лестница.',
      },
      {
        src: '/mariel/urino/22.jpg',
        alt: 'Годы строительства с 1874 по 1915 на древнеславянском.',
      },
      { src: '/mariel/urino/23.jpg', alt: '' },
      { src: '/mariel/urino/24.jpg', alt: '' },
      {
        src: '/mariel/urino/25.jpg',
        alt: 'Бильбо передал права на Юрино сыну — тирану Сергею Васильевичу. ',
      },
      {
        src: '/mariel/urino/26.jpg',
        alt: 'Основной строитель и владелец замка. Внучатый племянник Бильбо — Василий Петрович.',
      },
      {
        src: '/mariel/urino/27.jpg',
        alt: 'Бильбо Беггинса мы узнали сразу. В России он более известен как Василий Сергеевич Шереметев. Именно он сидит на Крутушке в Богородске. Именно он и купил усадьбу в 1812 г. за 350 тысяч рублей.',
      },
      { src: '/mariel/urino/28.jpg', alt: '' },
      { src: '/mariel/urino/29.jpg', alt: 'Скобелев был родным братом хозяйки.' },
      { src: '/mariel/urino/30.jpg', alt: 'Портал двери в большой зале.' },
      { src: '/mariel/urino/31.jpg', alt: 'Верещагин.' },
      { src: '/mariel/urino/32.jpg', alt: '' },
      { src: '/mariel/urino/33.jpg', alt: 'Айвазовский бывал в Юрино.' },
      { src: '/mariel/urino/34.jpg', alt: 'Оригинал в музее.' },
      { src: '/mariel/urino/35.jpg', alt: 'Где-то в подвалах замка спрятан клад.' },
      {
        src: '/mariel/urino/36.jpg',
        alt: 'В замке есть и привидение. По легенде тиран Сергей Васильевич приказал заживо замуровать крепостную девушку, отказавшую ему в праве первой брачной ночи.',
      },
      { src: '/mariel/urino/37.jpg', alt: '' },
      { src: '/mariel/urino/38.jpg', alt: '' },
      { src: '/mariel/urino/39.jpg', alt: '' },
      { src: '/mariel/urino/40.jpg', alt: '' },
    ],
  },
  {
    title: 'Карл Брюллов\n"Гадающая Светлана"',
    data: '5 января 2024 года',
    category: ['all', 'nizh'],
    photos: [
      {
        src: '/nizh/svetlana/0.jpg',
        alt: 'Раз в крещенский вечерок\nДевушки гадали:\nЗа ворота башмачок,\nСняв с ноги, бросали;\nСнег пололи; под окном\nСлушали; кормили\nСчетным курицу зерном;\nЯрый воск топили;\nВ чашу с чистою водой\nКлали перстень золотой,\nСерьги изумрудны;\nРасстилали белый плат\nИ над чашей пели в лад\nПесенки подблюдны.\n/В.А.Жуковский/',
      },
      { src: '/nizh/svetlana/1.jpg', alt: '' },
    ],
  },
  {
    title: 'Нижегородский художественный музей',
    data: '5 января 2024 года',
    category: ['all', 'nizh'],
    photos: [
      { src: '/nizh/artmuseum/0.jpg', alt: 'Макс у камня основания Нижнего Новгорода' },
      { src: '/nizh/artmuseum/1.jpg', alt: '' },
      { src: '/nizh/artmuseum/2.jpg', alt: '' },
      { src: '/nizh/artmuseum/3.jpg', alt: '' },
      { src: '/nizh/artmuseum/4.jpg', alt: '' },
      { src: '/nizh/artmuseum/5.jpg', alt: '' },
      { src: '/nizh/artmuseum/6.jpg', alt: '' },
      { src: '/nizh/artmuseum/7.jpg', alt: '' },
      { src: '/nizh/artmuseum/8.jpg', alt: '' },
      { src: '/nizh/artmuseum/9.jpg', alt: '' },
      { src: '/nizh/artmuseum/10.jpg', alt: '' },
      { src: '/nizh/artmuseum/11.jpg', alt: '' },
      { src: '/nizh/artmuseum/12.jpg', alt: '' },
      { src: '/nizh/artmuseum/13.jpg', alt: '' },
      { src: '/nizh/artmuseum/14.jpg', alt: '' },
      { src: '/nizh/artmuseum/15.jpg', alt: '' },
      { src: '/nizh/artmuseum/16.jpg', alt: '' },
      { src: '/nizh/artmuseum/17.jpg', alt: '' },
      { src: '/nizh/artmuseum/18.jpg', alt: '' },
      { src: '/nizh/artmuseum/19.jpg', alt: '' },
      { src: '/nizh/artmuseum/20.jpg', alt: '' },
      { src: '/nizh/artmuseum/21.jpg', alt: '' },
      { src: '/nizh/artmuseum/22.jpg', alt: '' },
      { src: '/nizh/artmuseum/23.jpg', alt: '' },
      { src: '/nizh/artmuseum/24.jpg', alt: '' },
    ],
  },
  {
    title: 'Новый год 2024',
    data: '30 декабря 2023 года',
    category: ['all', 'nizh'],
    photos: [
      { src: '/nizh/ny2024/0.jpg', alt: 'Новый год 2024' },
      { src: '/nizh/ny2024/1.jpg', alt: '' },
      { src: '/nizh/ny2024/2.jpg', alt: '' },
      { src: '/nizh/ny2024/3.jpg', alt: '' },
      { src: '/nizh/ny2024/4.jpg', alt: '' },
      { src: '/nizh/ny2024/5.jpg', alt: '' },
      { src: '/nizh/ny2024/6.jpg', alt: '' },
      { src: '/nizh/ny2024/7.jpg', alt: '' },
      { src: '/nizh/ny2024/8.jpg', alt: '' },
      { src: '/nizh/ny2024/9.jpg', alt: '' },
      { src: '/nizh/ny2024/10.jpg', alt: '' },
      { src: '/nizh/ny2024/11.jpg', alt: '' },
      { src: '/nizh/ny2024/12.jpg', alt: '' },
      { src: '/nizh/ny2024/13.jpg', alt: '' },
      { src: '/nizh/ny2024/14.jpg', alt: '' },
      { src: '/nizh/ny2024/15.jpg', alt: '' },
    ],
  },
  {
    title: 'Макарий',
    data: '2 декабря 2023 года',
    category: ['all', 'nizh'],
    photos: [
      { src: '/nizh/makaryi/0.jpg', alt: 'Макарий' },
      { src: '/nizh/makaryi/1.jpg', alt: '' },
      { src: '/nizh/makaryi/2.jpg', alt: '' },
      { src: '/nizh/makaryi/3.jpg', alt: '' },
      { src: '/nizh/makaryi/4.jpg', alt: '' },
      { src: '/nizh/makaryi/5.jpg', alt: '' },
      { src: '/nizh/makaryi/6.jpg', alt: '' },
      { src: '/nizh/makaryi/7.jpg', alt: '' },
      { src: '/nizh/makaryi/8.jpg', alt: '' },
      { src: '/nizh/makaryi/9.jpg', alt: '' },
      { src: '/nizh/makaryi/10.jpg', alt: '' },
      { src: '/nizh/makaryi/11.jpg', alt: '' },
      { src: '/nizh/makaryi/12.jpg', alt: '' },
      { src: '/nizh/makaryi/13.jpg', alt: '' },
      { src: '/nizh/makaryi/14.jpg', alt: '' },
      { src: '/nizh/makaryi/15.jpg', alt: '' },
      { src: '/nizh/makaryi/16.jpg', alt: '' },
      { src: '/nizh/makaryi/17.jpg', alt: '' },
    ],
  },
  {
    title: 'Муром',
    data: '4 ноября 2023 года',
    category: ['all', 'mariel'],
    photos: [
      { src: '/vlad/murom/0.jpg', alt: 'Муром' },
      { src: '/vlad/murom/1.jpg', alt: '' },
      { src: '/vlad/murom/2.jpg', alt: '' },
      { src: '/vlad/murom/3.jpg', alt: '' },
      { src: '/vlad/murom/4.jpg', alt: '' },
      { src: '/vlad/murom/5.jpg', alt: '' },
      { src: '/vlad/murom/6.jpg', alt: '' },
      { src: '/vlad/murom/7.jpg', alt: '' },
      { src: '/vlad/murom/8.jpg', alt: '' },
      { src: '/vlad/murom/9.jpg', alt: '' },
      { src: '/vlad/murom/10.jpg', alt: '' },
      { src: '/vlad/murom/11.jpg', alt: '' },
      { src: '/vlad/murom/12.jpg', alt: '' },
      { src: '/vlad/murom/13.jpg', alt: '' },
      { src: '/vlad/murom/14.jpg', alt: '' },
      { src: '/vlad/murom/15.jpg', alt: '' },
      { src: '/vlad/murom/16.jpg', alt: '' },
      { src: '/vlad/murom/17.jpg', alt: '' },
      { src: '/vlad/murom/18.jpg', alt: '' },
      { src: '/vlad/murom/19.jpg', alt: '' },
      { src: '/vlad/murom/20.jpg', alt: '' },
      { src: '/vlad/murom/21.jpg', alt: '' },
      { src: '/vlad/murom/22.jpg', alt: '' },
      { src: '/vlad/murom/23.jpg', alt: '' },
      { src: '/vlad/murom/24.jpg', alt: '' },
      { src: '/vlad/murom/25.jpg', alt: '' },
      { src: '/vlad/murom/26.jpg', alt: '' },
      { src: '/vlad/murom/27.jpg', alt: '' },
      { src: '/vlad/murom/28.jpg', alt: '' },
      { src: '/vlad/murom/29.jpg', alt: '' },
      { src: '/vlad/murom/30.jpg', alt: '' },
      { src: '/vlad/murom/31.jpg', alt: '' },
      { src: '/vlad/murom/32.jpg', alt: '' },
      { src: '/vlad/murom/33.jpg', alt: '' },
      { src: '/vlad/murom/34.jpg', alt: '' },
      { src: '/vlad/murom/35.jpg', alt: '' },
      { src: '/vlad/murom/36.jpg', alt: '' },
      { src: '/vlad/murom/37.jpg', alt: '' },
      { src: '/vlad/murom/38.jpg', alt: '' },
      { src: '/vlad/murom/39.jpg', alt: '' },
      { src: '/vlad/murom/40.jpg', alt: '' },
    ],
  },
  {
    title: 'Грибочки',
    data: '13 сентября, 2023 год',
    category: ['all', 'big'],
    photos: [
      { src: '/nizh/mushroom/0.jpg', alt: 'Под берёзой.' },
      { src: '/nizh/mushroom/1.jpg', alt: 'Под осиной.' },
      { src: '/nizh/mushroom/2.jpg', alt: 'Белый.' },
      { src: '/nizh/mushroom/3.jpg', alt: 'Ещё белый.' },
      { src: '/nizh/mushroom/4.jpg', alt: 'Плаун Булавовидный.' },
      { src: '/nizh/mushroom/5.jpg', alt: 'Дождевик.' },
      { src: '/nizh/mushroom/6.jpg', alt: 'Мухомор.' },
      { src: '/nizh/mushroom/7.jpg', alt: 'Подберёзовик.' },
      { src: '/nizh/mushroom/8.jpg', alt: 'Клядония.' },
      { src: '/nizh/mushroom/9.jpg', alt: 'Волнушки волнуются.' },
      { src: '/nizh/mushroom/10.jpg', alt: 'Волнушка. Волжанка ореховая.' },
      { src: '/nizh/mushroom/11.jpg', alt: 'Скинула она свою шкурку и обернулась...' },
      { src: '/nizh/mushroom/12.jpg', alt: 'Маслёнок.' },
      { src: '/nizh/mushroom/13.jpg', alt: 'Белый.' },
      { src: '/nizh/mushroom/14.jpg', alt: 'Белый.' },
      { src: '/nizh/mushroom/15.jpg', alt: 'Подосиновик.' },
      { src: '/nizh/mushroom/16.jpg', alt: 'Белый.' },
      { src: '/nizh/mushroom/17.jpg', alt: 'Белый.' },
    ],
  },
  {
    title: 'Противолавинный барьер',
    data: '23 августа 2023 года',
    category: ['all', 'big'],
    photos: [
      { src: '/camp/zikkur/0.jpg', alt: 'Противолавинный барьер' },
      { src: '/camp/zikkur/1.jpg', alt: '' },
      { src: '/camp/zikkur/2.jpg', alt: '' },
      { src: '/camp/zikkur/3.jpg', alt: '' },
      { src: '/camp/zikkur/4.jpg', alt: '' },
      { src: '/camp/zikkur/5.jpg', alt: '' },
      { src: '/camp/zikkur/6.jpg', alt: '' },
      { src: '/camp/zikkur/7.jpg', alt: '' },
      { src: '/camp/zikkur/8.jpg', alt: '' },
      { src: '/camp/zikkur/9.jpg', alt: '' },
    ],
  },
  {
    title: 'Чегет',
    data: '24 августа 2023 года',
    category: ['all', 'big'],
    photos: [
      { src: '/camp/cheget/0.jpg', alt: 'Чегет' },
      { src: '/camp/cheget/1.jpg', alt: '' },
      { src: '/camp/cheget/2.jpg', alt: '' },
      { src: '/camp/cheget/3.jpg', alt: '' },
      { src: '/camp/cheget/4.jpg', alt: '' },
      { src: '/camp/cheget/5.jpg', alt: '' },
      { src: '/camp/cheget/6.jpg', alt: '' },
      { src: '/camp/cheget/7.jpg', alt: '' },
      { src: '/camp/cheget/8.jpg', alt: '' },
      { src: '/camp/cheget/9.jpg', alt: '' },
      { src: '/camp/cheget/10.jpg', alt: '' },
      { src: '/camp/cheget/11.jpg', alt: '' },
      { src: '/camp/cheget/12.jpg', alt: '' },
      { src: '/camp/cheget/13.jpg', alt: '' },
      { src: '/camp/cheget/14.jpg', alt: '' },
      { src: '/camp/cheget/15.jpg', alt: '' },
      { src: '/camp/cheget/16.jpg', alt: '' },
      { src: '/camp/cheget/17.jpg', alt: '' },
      { src: '/camp/cheget/18.jpg', alt: '' },
      { src: '/camp/cheget/19.jpg', alt: '' },
      { src: '/camp/cheget/20.jpg', alt: '' },
      { src: '/camp/cheget/21.jpg', alt: '' },
      { src: '/camp/cheget/22.jpg', alt: '' },
      { src: '/camp/cheget/23.jpg', alt: '' },
      { src: '/camp/cheget/24.jpg', alt: '' },
      { src: '/camp/cheget/25.jpg', alt: '' },
      { src: '/camp/cheget/26.jpg', alt: '' },
      { src: '/camp/cheget/27.jpg', alt: '' },
      { src: '/camp/cheget/28.jpg', alt: '' },
      { src: '/camp/cheget/29.jpg', alt: '' },
      { src: '/camp/cheget/30.jpg', alt: '' },
      { src: '/camp/cheget/31.jpg', alt: '' },
      { src: '/camp/cheget/32.jpg', alt: '' },
      { src: '/camp/cheget/33.jpg', alt: '' },
      { src: '/camp/cheget/34.jpg', alt: '' },
      { src: '/camp/cheget/35.jpg', alt: '' },
      { src: '/camp/cheget/36.jpg', alt: '' },
    ],
  },
  {
    title: 'Ергаки',
    data: '2011 год',
    category: ['all', 'big'],
    photos: [
      { src: '/camp/ergaki/fone.jpg', alt: 'Ергаки' },
      { src: '/camp/ergaki/puteshest_50b.jpg', alt: '' },
      { src: '/camp/ergaki/puteshest_52b.jpg', alt: '' },
      { src: '/camp/ergaki/puteshest_53b.jpg', alt: '' },
      { src: '/camp/ergaki/puteshest_54b.jpg', alt: '' },
      { src: '/camp/ergaki/puteshest_55b.jpg', alt: '' },
      { src: '/camp/ergaki/puteshest_56b.jpg', alt: '' },
    ],
  },
];
